const iconOptions = [
  { icon: '', label: 'Selecione um icone' },
  { icon: '/icons/order/food/arroz-japones.svg', label: 'Arroz Japones' },
  { icon: '/icons/order/food/bife.svg', label: 'Bife' },
  { icon: '/icons/order/food/bolo.svg', label: 'Bolo' },
  { icon: '/icons/order/food/cachorro-quente.svg', label: 'Cachorro quente' },
  { icon: '/icons/order/food/carne.png', label: 'Carne' },
  { icon: '/icons/order/food/churrasco.png', label: 'Churrasco' },
  { icon: '/icons/order/food/coco.svg', label: 'Coco' },
  { icon: '/icons/order/food/doce.png', label: 'Doce' },
  { icon: '/icons/order/food/frango-frito.svg', label: 'Frango Frito' },
  { icon: '/icons/order/food/frutos do mar.png', label: 'Frutos do mar' },
  { icon: '/icons/order/food/hamburger.svg', label: 'Hamburger' },
  { icon: '/icons/order/food/hamburguer.png', label: 'Hamgurguer 2' },
  { icon: '/icons/order/food/massas.png', label: 'Massas' },
  { icon: '/icons/order/food/paes.png', label: 'Paes' },
  { icon: '/icons/order/food/pao.svg', label: 'Pão' },
  { icon: '/icons/order/food/pastel frito.png', label: 'Pastel frito' },
  { icon: '/icons/order/food/peixe.png', label: 'Peixe' },
  { icon: '/icons/order/food/pizza-completa.svg', label: 'Pizza completa' },
  { icon: '/icons/order/food/pizza-fatia.svg', label: 'Pizza fatia' },
  { icon: '/icons/order/food/porcao.png', label: 'Porção' },
  { icon: '/icons/order/food/queijo.svg', label: 'Queijo' },
  { icon: '/icons/order/food/raspadinha-gelo.svg', label: 'Raspadinha' },
  { icon: '/icons/order/food/refri-petisco.svg', label: 'Refrigerante com petisco' },
  { icon: '/icons/order/food/salada.png', label: 'Salada' },
  { icon: '/icons/order/food/salgado.png', label: 'Salgado' },
  { icon: '/icons/order/food/sopas.png', label: 'Sopas' },
  { icon: '/icons/order/food/sorvete.png', label: 'Sorvete' },
  { icon: '/icons/order/food/taco.svg', label: 'Taco' },
  { icon: '/icons/order/food/tapioca.png', label: 'Tapioca' },
  { icon: '/icons/order/food/torta.png', label: 'Torta' },
  { icon: '/icons/order/food/uva.svg', label: 'Uva' },
  { icon: '/icons/order/food/vegetariano.png', label: 'Vegetariano' },
  { icon: '/icons/order/food/vinho-pao-queijo.svg', label: 'Vinho, pão e queijo' },
]

export default iconOptions