const iconOptions = [
  { icon: '/icons/order/food/arroz-japones.svg', label: 'Arroz Japones' },
  { icon: '/icons/order/food/bife.svg', label: 'Bife' },
  { icon: '/icons/order/food/bolo.svg', label: 'Bolo' },
  { icon: '/icons/order/food/cachorro-quente.svg', label: 'Cachorro quente' },
  { icon: '/icons/order/food/carne.png', label: 'Carne' },
  { icon: '/icons/order/food/churrasco.png', label: 'Churrasco' },
  { icon: '/icons/order/food/coco.svg', label: 'Coco' },
  { icon: '/icons/order/food/doce.png', label: 'Doce' },
  { icon: '/icons/order/food/frango-frito.svg', label: 'Frango Frito' },
  { icon: '/icons/order/food/frutos do mar.png', label: 'Frutos do mar' },
  { icon: '/icons/order/food/hamburger.svg', label: 'Hamburger' },
  { icon: '/icons/order/food/hamburguer.png', label: 'Hamgurguer 2' },
  { icon: '/icons/order/food/massas.png', label: 'Massas' },
  { icon: '/icons/order/food/paes.png', label: 'Paes' },
  { icon: '/icons/order/food/pao.svg', label: 'Pão' },
  { icon: '/icons/order/food/pastel frito.png', label: 'Pastel frito' },
  { icon: '/icons/order/food/peixe.png', label: 'Peixe' },
  { icon: '/icons/order/food/pizza-completa.svg', label: 'Pizza completa' },
  { icon: '/icons/order/food/pizza-fatia.svg', label: 'Pizza fatia' },
  { icon: '/icons/order/food/porcao.png', label: 'Porção' },
  { icon: '/icons/order/food/queijo.svg', label: 'Queijo' },
  { icon: '/icons/order/food/raspadinha-gelo.svg', label: 'Raspadinha' },
  { icon: '/icons/order/food/refri-petisco.svg', label: 'Refrigerante com petisco' },
  { icon: '/icons/order/food/salada.png', label: 'Salada' },
  { icon: '/icons/order/food/salgado.png', label: 'Salgado' },
  { icon: '/icons/order/food/sopas.png', label: 'Sopas' },
  { icon: '/icons/order/food/sorvete.png', label: 'Sorvete' },
  { icon: '/icons/order/food/taco.svg', label: 'Taco' },
  { icon: '/icons/order/food/tapioca.png', label: 'Tapioca' },
  { icon: '/icons/order/food/torta.png', label: 'Torta' },
  { icon: '/icons/order/food/uva.svg', label: 'Uva' },
  { icon: '/icons/order/food/vegetariano.png', label: 'Vegetariano' },
  { icon: '/icons/order/food/vinho-pao-queijo.svg', label: 'Vinho, pão e queijo' },
  { icon: '/icons/order/food/ovo-salada.svg', label: 'Ovo e salada' },
  
  { icon: '/icons/order/drink/cafe.svg', label: 'Café' },
  { icon: '/icons/order/drink/cerveja.svg', label: 'Cerveja' },
  { icon: '/icons/order/drink/cha.png', label: 'cha' },
  { icon: '/icons/order/drink/drink.svg', label: 'Drink' },
  { icon: '/icons/order/drink/drinks.svg', label: 'Drinks' },
  { icon: '/icons/order/drink/espumante.png', label: 'Espumante' },
  { icon: '/icons/order/drink/gin.png', label: 'Gin' },
  { icon: '/icons/order/drink/licor.png', label: 'Licor' },
  { icon: '/icons/order/drink/refrigerante.svg', label: 'Refrigerante' },
  { icon: '/icons/order/drink/rum.png', label: 'Rum' },
  { icon: '/icons/order/drink/tequila.png', label: 'Tequila' },
  { icon: '/icons/order/drink/vinho.svg', label: 'Vinho' },
  { icon: '/icons/order/drink/vodka.png', label: 'Vodka' },
  { icon: '/icons/order/drink/whisky.png', label: 'Whisky' },
  
]

export default iconOptions